server:
  port: 8082

spring:
  application:
    name: my-second-service

#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka